INPUT_FILE = "input/2017 Data- Challenge BI - 2017 Data.csv"
POSTGRES_URL = "localhost"
POSTGRES_DATABASE = "postgres"
POSTGRES_DBTABLE = "loadsmart"
POSTGRES_USER = "postgres"
POSTGRES_PASSWORD = "admin1234"